#!/bin/bash

../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-agecheck-1" --url "https://liveinmac.com/lospo/agecheck/age-check/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-agecheck-2" --url "https://liveinmac.com/lospo/agecheck/age-check-1/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-bot-captcha" --url "https://liveinmac.com/lospo/botcheck/bot-captcha/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-bot-check" --url "https://liveinmac.com/lospo/botcheck/bot-check/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-bot-check3" --url "https://liveinmac.com/lospo/botcheck/bot-check-3/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-bot-detect" --url "https://liveinmac.com/lospo/botcheck/bot-detect/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-download" --url "https://liveinmac.com/lospo/download/download/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-download1" --url "https://liveinmac.com/lospo/download/download1/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-games-mario" --url "https://liveinmac.com/lospo/games/mario/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-general-access-website" --url "https://liveinmac.com/lospo/general/access-website/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-general-progress" --url "https://liveinmac.com/lospo/general/progress/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-general-weather" --url "https://liveinmac.com/lospo/general/weather/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-sweeps-boxes-italy" --url "https://liveinmac.com/lospo/sweeps/boxesit/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-sweeps-gift-card" --url "https://liveinmac.com/lospo/sweeps/gift-card/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-sweeps-quiz-italy" --url "https://liveinmac.com/lospo/sweeps/quizit/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-sweeps-quiz2-italy" --url "https://liveinmac.com/lospo/sweeps/quizit2/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-sweeps-sweep" --url "https://liveinmac.com/lospo/sweeps/sweep/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-sweeps-winiphone" --url "https://liveinmac.com/lospo/sweeps/winiphone/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-sweeps-preland-boxes-italy" --url "https://liveinmac.com/lospo/sweeps/pre-boxes-it/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-video-bigplay" --url "https://liveinmac.com/lospo/video/play/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-video-video" --url "https://liveinmac.com/lospo/video/video/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-video-video1" --url "https://liveinmac.com/lospo/video/video-1/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-video-video2" --url "https://liveinmac.com/lospo/video/video-2/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-video-video3" --url "https://liveinmac.com/lospo/video/video-3/?external_id={external_id}"
../core/target/debug/majorka-cli --redis redis://127.0.0.1:6380/ offers create --name "lospo-push-video-video4" --url "https://liveinmac.com/lospo/video/video-4/?external_id={external_id}"
